// ============================================================
// スキーマ定義（db.py の SCHEMA_SQL をそのまま移植）
// 主キーはすべて意味を持たないサロゲートキー。標準コード（JIS 等）は
// ただの属性 + UNIQUE 制約として持つ。
// ============================================================

export const SCHEMA_SQL = `
-- 住所マスタ 3 テーブル
CREATE TABLE IF NOT EXISTS prefectures (
    id       integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    jis_code text NOT NULL UNIQUE,   -- JIS X 0401 2桁（先頭ゼロ保持のため text。例 '13'）
    name     text NOT NULL           -- 例 '東京都'
);

CREATE TABLE IF NOT EXISTS shikuchoson (
    id            integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    prefecture_id integer NOT NULL REFERENCES prefectures(id),
    jis_code      text NOT NULL UNIQUE,  -- JIS X 0402 5桁（例 '13106'）
    name          text NOT NULL          -- 例 '台東区'
);
CREATE INDEX IF NOT EXISTS idx_shikuchoson_pref ON shikuchoson (prefecture_id);

CREATE TABLE IF NOT EXISTS chibankuiki (
    -- 地番区域（大字町丁目）。地番はこの区域内で一意になる
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shikuchoson_id integer NOT NULL REFERENCES shikuchoson(id),
    choaza_code    text NOT NULL,     -- 大字町丁目コード12桁の下6桁
    name           text NOT NULL,     -- 大字町丁目名（位置参照情報の表記そのまま。例 '下谷一丁目'）
    lat            double precision,  -- 代表点（位置参照情報由来）
    lng            double precision,
    UNIQUE (shikuchoson_id, choaza_code),
    UNIQUE (shikuchoson_id, name)
);
CREATE INDEX IF NOT EXISTS idx_chibankuiki_shikuchoson ON chibankuiki (shikuchoson_id);

CREATE TABLE IF NOT EXISTS parcels (
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chibankuiki_id integer NOT NULL REFERENCES chibankuiki(id),  -- 地番区域マスタ参照（所在の正本）
    chiban         text NOT NULL,
    geometry       jsonb NOT NULL,    -- GeoJSON Polygon（[lng,lat]・末尾は始点の繰り返し）
    UNIQUE (chibankuiki_id, chiban)   -- 地番は地番区域内で一意
);

CREATE TABLE IF NOT EXISTS projects (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    description text NOT NULL DEFAULT '',
    polygon     jsonb,                     -- 案件領域 [[lat,lng], ...]
    address     text,
    access      text,
    staff       text,                      -- 担当者名
    current_bcr numeric,                   -- 現況建蔽率（%）
    current_far numeric,
    target_far  numeric,
    zoning      text,                      -- 用途地域（例「商業」）
    front_roads jsonb NOT NULL DEFAULT '[]',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lands (
    id          text PRIMARY KEY,
    project_id  integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    parcel_id   integer NOT NULL REFERENCES parcels(id),
    description text NOT NULL DEFAULT '',
    area_m2     numeric NOT NULL DEFAULT 0,  -- 面積（㎡。登記の正本単位。坪は表示時に換算）
    status      text NOT NULL DEFAULT 'target' CHECK (status IN ('target', 'acquired')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, parcel_id)
);
CREATE INDEX IF NOT EXISTS idx_lands_project ON lands (project_id, created_at);

CREATE TABLE IF NOT EXISTS land_owners (
    id        integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順（= owners 配列の並び）
    land_id   text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    name      text NOT NULL,
    share_num integer,
    share_den integer,
    address     text NOT NULL DEFAULT '',  -- 所有者住所
    reg_date    date,                      -- 登記日（未設定は NULL ↔ API では ''）
    reg_cause   text NOT NULL DEFAULT '',  -- 登記原因（相続/売買/遺贈 等）
    description text NOT NULL DEFAULT '',  -- 備考
    CHECK ((share_num IS NULL) = (share_den IS NULL)),
    CHECK (share_den IS NULL OR share_den > 0)
);
CREATE INDEX IF NOT EXISTS idx_land_owners_land ON land_owners (land_id, id);

-- 抵当権（土地の子。owners と同型の全置換・追加順保持）
CREATE TABLE IF NOT EXISTS land_mortgages (
    id      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    land_id text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    date    date,                          -- 設定日（未設定は NULL ↔ API では ''）
    amount  numeric,                       -- 債権額（万円）。未設定は NULL
    holder  text NOT NULL DEFAULT ''       -- 抵当権者
);
CREATE INDEX IF NOT EXISTS idx_land_mortgages_land ON land_mortgages (land_id, id);

-- 建物（土地の子。土地とは別に登記され地権者も異なりうる。更地は建物なし）
CREATE TABLE IF NOT EXISTS buildings (
    id           text PRIMARY KEY,
    land_id      text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    kaoku_number text NOT NULL DEFAULT '',   -- 家屋番号
    structure    text NOT NULL DEFAULT '',   -- 構造（例「木造2階建」）
    usage        text NOT NULL DEFAULT '',   -- 種類・用途（非予約語。静的 INSERT で使うため引用符不要）
    floor_area   numeric,                    -- 床面積（㎡）。未設定は NULL
    built_date   date,                       -- 新築年月日（未設定は NULL ↔ API では ''）
    description  text NOT NULL DEFAULT '',   -- 備考
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_buildings_land ON buildings (land_id, created_at, id);

CREATE TABLE IF NOT EXISTS building_owners (
    id          integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順（= owners 配列の並び）
    building_id text NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    name        text NOT NULL,
    share_num   integer,
    share_den   integer,
    address     text NOT NULL DEFAULT '',    -- 所有者住所
    reg_date    date,                        -- 登記日（未設定は NULL ↔ API では ''）
    reg_cause   text NOT NULL DEFAULT '',    -- 登記原因（相続/売買/遺贈 等）
    description text NOT NULL DEFAULT '',    -- 備考
    CHECK ((share_num IS NULL) = (share_den IS NULL)),
    CHECK (share_den IS NULL OR share_den > 0)
);
CREATE INDEX IF NOT EXISTS idx_building_owners_building ON building_owners (building_id, id);

-- 抵当権（建物の子。land_mortgages と同型）
CREATE TABLE IF NOT EXISTS building_mortgages (
    id          integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    building_id text NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    date        date,                        -- 設定日（未設定は NULL ↔ API では ''）
    amount      numeric,                     -- 債権額（万円）。未設定は NULL
    holder      text NOT NULL DEFAULT ''     -- 抵当権者
);
CREATE INDEX IF NOT EXISTS idx_building_mortgages_building ON building_mortgages (building_id, id);

CREATE TABLE IF NOT EXISTS visits (
    id            text PRIMARY KEY,
    land_id       text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    user_name     text NOT NULL DEFAULT '',
    comment       text NOT NULL DEFAULT '',
    date          timestamptz NOT NULL DEFAULT now(),
    direct_or_tel text NOT NULL DEFAULT '',
    meeting_type  text NOT NULL DEFAULT '',
    next_date     timestamptz,             -- 未設定は NULL（API では '' に変換）
    progress      text NOT NULL DEFAULT '',
    principal     text NOT NULL DEFAULT 'principal'
);
CREATE INDEX IF NOT EXISTS idx_visits_land ON visits (land_id, date);

CREATE TABLE IF NOT EXISTS app_meta (
    key   text PRIMARY KEY,
    value text NOT NULL
);
`;
