// ============================================================
// スキーマ定義（db.py の SCHEMA_SQL をそのまま移植）
// 主キーはすべて意味を持たないサロゲートキー。標準コード（JIS 等）は
// ただの属性 + UNIQUE 制約として持つ。
// ============================================================

export const SCHEMA_SQL = `
-- 住所マスタ 3 テーブル
CREATE TABLE IF NOT EXISTS prefectures (
    id       integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    jis_code text NOT NULL UNIQUE,   -- JIS X 0401 2桁（先頭ゼロ保持のため text。例 '13'）
    name     text NOT NULL           -- 例 '東京都'
);

CREATE TABLE IF NOT EXISTS shikuchoson (
    id            integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    prefecture_id integer NOT NULL REFERENCES prefectures(id),
    jis_code      text NOT NULL UNIQUE,  -- JIS X 0402 5桁（例 '13106'）
    name          text NOT NULL          -- 例 '台東区'
);
CREATE INDEX IF NOT EXISTS idx_shikuchoson_pref ON shikuchoson (prefecture_id);

CREATE TABLE IF NOT EXISTS chibankuiki (
    -- 地番区域（大字町丁目）。地番はこの区域内で一意になる
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shikuchoson_id integer NOT NULL REFERENCES shikuchoson(id),
    choaza_code    text NOT NULL,     -- 大字町丁目コード12桁の下6桁
    name           text NOT NULL,     -- 大字町丁目名（位置参照情報の表記そのまま。例 '下谷一丁目'）
    lat            double precision,  -- 代表点（位置参照情報由来）
    lng            double precision,
    UNIQUE (shikuchoson_id, choaza_code),
    UNIQUE (shikuchoson_id, name)
);
CREATE INDEX IF NOT EXISTS idx_chibankuiki_shikuchoson ON chibankuiki (shikuchoson_id);

CREATE TABLE IF NOT EXISTS parcels (
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chibankuiki_id integer NOT NULL REFERENCES chibankuiki(id),  -- 地番区域マスタ参照（所在の正本）
    chiban         text NOT NULL,
    geometry       jsonb NOT NULL,    -- GeoJSON Polygon（[lng,lat]・末尾は始点の繰り返し）
    UNIQUE (chibankuiki_id, chiban)   -- 地番は地番区域内で一意
);

CREATE TABLE IF NOT EXISTS projects (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    description text NOT NULL DEFAULT '',
    polygon     jsonb,                     -- 案件領域 [[lat,lng], ...]
    address     text,
    access      text,
    current_far numeric,
    target_far  numeric,
    front_roads jsonb NOT NULL DEFAULT '[]',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lands (
    id          text PRIMARY KEY,
    project_id  integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    parcel_id   integer NOT NULL REFERENCES parcels(id),
    description text NOT NULL DEFAULT '',
    area_tsubo  numeric NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'target' CHECK (status IN ('target', 'acquired')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, parcel_id)
);
CREATE INDEX IF NOT EXISTS idx_lands_project ON lands (project_id, created_at);

CREATE TABLE IF NOT EXISTS land_owners (
    id        integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順（= owners 配列の並び）
    land_id   text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    name      text NOT NULL,
    share_num integer,
    share_den integer,
    CHECK ((share_num IS NULL) = (share_den IS NULL)),
    CHECK (share_den IS NULL OR share_den > 0)
);
CREATE INDEX IF NOT EXISTS idx_land_owners_land ON land_owners (land_id, id);

-- 建物（棟単位）。土地の上の建物で、所有形態で地権者の持ち方が変わる:
--   sole  = 一棟所有（単独・共有）: 所有者は building_owners に持つ
--   kubun = 区分所有（分譲マンション等）: 所有者は専有部分 building_units ごとに持つ
CREATE TABLE IF NOT EXISTS buildings (
    id               text PRIMARY KEY,
    land_id          text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    name             text NOT NULL DEFAULT '',   -- 建物名称（例「上野パークハイツ」。空可）
    house_number     text NOT NULL DEFAULT '',   -- 家屋番号（例「24番3」）
    structure        text NOT NULL DEFAULT '',   -- 構造・階数（例「木造瓦葺2階建」）
    floor_area_tsubo numeric,                    -- 延床面積（坪）。未把握は NULL
    ownership_type   text NOT NULL DEFAULT 'sole' CHECK (ownership_type IN ('sole', 'kubun')),
    description      text NOT NULL DEFAULT '',
    created_at       timestamptz NOT NULL DEFAULT now(),
    updated_at       timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_buildings_land ON buildings (land_id, created_at);

-- 一棟所有（sole）の所有者。land_owners と同形（持分は分子・分母の整数2列）
CREATE TABLE IF NOT EXISTS building_owners (
    id          integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順（= owners 配列の並び）
    building_id text NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    name        text NOT NULL,
    share_num   integer,
    share_den   integer,
    CHECK ((share_num IS NULL) = (share_den IS NULL)),
    CHECK (share_den IS NULL OR share_den > 0)
);
CREATE INDEX IF NOT EXISTS idx_building_owners_building ON building_owners (building_id, id);

-- 専有部分（区分所有 kubun のみ）。敷地権割合は土地に対する共有持分
CREATE TABLE IF NOT EXISTS building_units (
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順
    building_id    text NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
    unit_number    text NOT NULL,      -- 部屋番号・専有部分の家屋番号（例「301」）
    site_share_num integer,            -- 敷地権割合（分子）。未把握は NULL
    site_share_den integer,
    description    text NOT NULL DEFAULT '',
    CHECK ((site_share_num IS NULL) = (site_share_den IS NULL)),
    CHECK (site_share_den IS NULL OR site_share_den > 0),
    UNIQUE (building_id, unit_number)
);
CREATE INDEX IF NOT EXISTS idx_building_units_building ON building_units (building_id, id);

-- 専有部分の区分所有者。building_owners と同形
CREATE TABLE IF NOT EXISTS building_unit_owners (
    id        integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順
    unit_id   integer NOT NULL REFERENCES building_units(id) ON DELETE CASCADE,
    name      text NOT NULL,
    share_num integer,
    share_den integer,
    CHECK ((share_num IS NULL) = (share_den IS NULL)),
    CHECK (share_den IS NULL OR share_den > 0)
);
CREATE INDEX IF NOT EXISTS idx_building_unit_owners_unit ON building_unit_owners (unit_id, id);

CREATE TABLE IF NOT EXISTS visits (
    id            text PRIMARY KEY,
    land_id       text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    user_name     text NOT NULL DEFAULT '',
    comment       text NOT NULL DEFAULT '',
    date          timestamptz NOT NULL DEFAULT now(),
    direct_or_tel text NOT NULL DEFAULT '',
    meeting_type  text NOT NULL DEFAULT '',
    next_date     timestamptz,             -- 未設定は NULL（API では '' に変換）
    progress      text NOT NULL DEFAULT '',
    principal     text NOT NULL DEFAULT 'principal'
);
CREATE INDEX IF NOT EXISTS idx_visits_land ON visits (land_id, date);

CREATE TABLE IF NOT EXISTS app_meta (
    key   text PRIMARY KEY,
    value text NOT NULL
);
`;
