#!/usr/bin/env python3
"""
共有データレイヤー（PostgreSQL 版）

旧 data.js が localStorage 上に持っていた案件・土地・訪問記録を PostgreSQL に
正規化テーブル（projects / lands / visits）で永続化する。筆マスタも parcels
テーブルに取り込み、土地の parcelId に外部キー制約を張る。
住所階層は住所マスタ 3 テーブル（prefectures / shikuchoson / chibankuiki）で持ち、
筆は地番区域（大字町丁目）への参照 (chibankuiki_id) で所在を表す。

設計上の不変条件（旧 data.js から引き継ぎ）:
    - 土地は筆マスタへの参照 (parcel_id) でのみ作成・変更できる
    - 町名 (aza)・地番 (chiban)・領域 (polygon) は読み出しのたびに
      parcels・chibankuiki から再導出する（lands には保存しない）
    - 1 案件内で同じ筆は重複できない（UNIQUE (project_id, parcel_id)）
    - 訪問記録は追加のみ（履歴のため編集・削除 API を持たない）
    - ID は意味を持たないサロゲートキー。JIS コード・町名・地番などの
      業務属性はただのカラム + UNIQUE 制約で表現する（ID から業務情報を読み取らない）

接続先は環境変数 DATABASE_URL（既定: docker-compose.yml の postgres:17）。
"""

import csv
import gzip
import json
import math
import os
import re
import secrets
from datetime import datetime, timedelta

import psycopg
from psycopg.rows import dict_row
from psycopg.types.json import Jsonb

DATABASE_URL = os.environ.get(
    "DATABASE_URL", "postgresql://chiban:chiban@localhost:5432/chiban"
)

_REPO_DIR = os.path.dirname(os.path.abspath(__file__))
KOUZU_JS_PATH = os.path.join(_REPO_DIR, "kouzu_xml_data.js")
# 台東区全図面のシード（tools/convert_kouzu_seed.py が生成。約5万筆）。
# 存在しない場合は kouzu_xml_data.js（5図面・595筆）にフォールバックする
PARCEL_SEED_PATH = os.path.join(_REPO_DIR, "kouzu_parcels_seed.json.gz")
# 住所マスタのシード（国土交通省「位置参照情報」大字・町丁目レベルの台東区抽出。Shift-JIS）
ADDRESS_CSV_PATH = os.path.join(_REPO_DIR, "13106_2025.csv")


class ApiError(Exception):
    """HTTP ステータス付きの業務エラー。メッセージはそのまま UI に出るので日本語で書く。"""

    def __init__(self, status, message):
        super().__init__(message)
        self.status = status
        self.message = message


def connect():
    return psycopg.connect(DATABASE_URL, row_factory=dict_row)


def _uuid():
    # 旧 data.js の uuid() と同じ「id_ + 8文字」形式（既存 URL・DOM 周りの想定を変えない）
    return "id_" + secrets.token_hex(4)


def _now():
    return datetime.now().astimezone()


# ============================================================
# スキーマ
# ============================================================

SCHEMA_SQL = """
-- 住所マスタ 3 テーブル。主キーはすべて意味を持たないサロゲートキーで、
-- JIS コード等の標準コードはただの属性 + UNIQUE 制約として持つ
CREATE TABLE IF NOT EXISTS prefectures (
    id       integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    jis_code text NOT NULL UNIQUE,   -- JIS X 0401 2桁（先頭ゼロ保持のため text。例 '13'）
    name     text NOT NULL           -- 例 '東京都'
);

CREATE TABLE IF NOT EXISTS shikuchoson (
    id            integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    prefecture_id integer NOT NULL REFERENCES prefectures(id),
    jis_code      text NOT NULL UNIQUE,  -- JIS X 0402 5桁（例 '13106'）。所属都道府県は FK が正本
    name          text NOT NULL          -- 例 '台東区'
);
CREATE INDEX IF NOT EXISTS idx_shikuchoson_pref ON shikuchoson (prefecture_id);

CREATE TABLE IF NOT EXISTS chibankuiki (
    -- 地番区域（大字町丁目）。地番はこの区域内で一意になる
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    shikuchoson_id integer NOT NULL REFERENCES shikuchoson(id),
    choaza_code    text NOT NULL,     -- 大字町丁目コード12桁の下6桁（大字下3桁+丁目3桁。国土地理協会コード互換。例 '001001'）
    name           text NOT NULL,     -- 大字町丁目名（位置参照情報の表記そのまま。例 '下谷一丁目'）。API・プルダウンの正本
    lat            double precision,  -- 代表点（位置参照情報由来）
    lng            double precision,
    UNIQUE (shikuchoson_id, choaza_code),  -- 6桁コードは市区町村内でのみ一意
    UNIQUE (shikuchoson_id, name)
);
CREATE INDEX IF NOT EXISTS idx_chibankuiki_shikuchoson ON chibankuiki (shikuchoson_id);

CREATE TABLE IF NOT EXISTS parcels (
    id             integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    chibankuiki_id integer NOT NULL REFERENCES chibankuiki(id),  -- 地番区域マスタ参照（所在の正本）
    chiban         text NOT NULL,
    geometry       jsonb NOT NULL,    -- GeoJSON Polygon（[lng,lat]・末尾は始点の繰り返し）
    UNIQUE (chibankuiki_id, chiban)   -- 地番は地番区域内で一意（町名→筆一覧の索引も兼ねる）
);

CREATE TABLE IF NOT EXISTS projects (
    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        text NOT NULL,
    description text NOT NULL DEFAULT '',
    polygon     jsonb,                     -- 案件領域 [[lat,lng], ...]
    address     text,
    access      text,
    current_far numeric,
    target_far  numeric,
    front_roads jsonb NOT NULL DEFAULT '[]',
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS lands (
    id          text PRIMARY KEY,
    project_id  integer NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
    parcel_id   integer NOT NULL REFERENCES parcels(id),
    description text NOT NULL DEFAULT '',
    area_tsubo  numeric NOT NULL DEFAULT 0,
    status      text NOT NULL DEFAULT 'target' CHECK (status IN ('target', 'acquired')),
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    UNIQUE (project_id, parcel_id)
);
CREATE INDEX IF NOT EXISTS idx_lands_project ON lands (project_id, created_at);

CREATE TABLE IF NOT EXISTS land_owners (
    id      integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,  -- 追加順（= owners 配列の並び）
    land_id text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    name      text NOT NULL,
    share_num integer,                        -- 持分の分子（持分指定なしは NULL）
    share_den integer,                        -- 持分の分母（持分指定なしは NULL）
    CHECK ((share_num IS NULL) = (share_den IS NULL)),  -- 分子・分母は揃って指定/未指定
    CHECK (share_den IS NULL OR share_den > 0)
);
CREATE INDEX IF NOT EXISTS idx_land_owners_land ON land_owners (land_id, id);

CREATE TABLE IF NOT EXISTS visits (
    id            text PRIMARY KEY,
    land_id       text NOT NULL REFERENCES lands(id) ON DELETE CASCADE,
    user_name     text NOT NULL DEFAULT '',
    comment       text NOT NULL DEFAULT '',
    date          timestamptz NOT NULL DEFAULT now(),
    direct_or_tel text NOT NULL DEFAULT '',
    meeting_type  text NOT NULL DEFAULT '',
    next_date     timestamptz,             -- 未設定は NULL（API では '' に変換）
    progress      text NOT NULL DEFAULT '',
    principal     text NOT NULL DEFAULT 'principal'
);
CREATE INDEX IF NOT EXISTS idx_visits_land ON visits (land_id, date);

CREATE TABLE IF NOT EXISTS app_meta (
    key   text PRIMARY KEY,
    value text NOT NULL
);
"""


def ensure_schema(conn):
    conn.execute(SCHEMA_SQL)


# ============================================================
# 筆マスタ（kouzu_xml_data.js → parcels テーブル）
# ============================================================

def _load_kouzu_features():
    """kouzu_xml_data.js から GeoJSON features を読み出す。
    `window.KOUZU_XML_DATA = {...};` 形式の自動生成ファイルなので、
    代入の右辺だけを JSON として取り出す。"""
    with open(KOUZU_JS_PATH, encoding="utf-8") as f:
        src = f.read()
    m = re.search(r"window\.KOUZU_XML_DATA\s*=\s*(\{.*\});?\s*$", src, re.S)
    if not m:
        raise RuntimeError("kouzu_xml_data.js から KOUZU_XML_DATA を抽出できません")
    data = json.loads(m.group(1))
    return data["geojson"]["features"]


def _load_seed_parcels():
    """筆マスタのシード行を返す。
    台東区全図面シード（kouzu_parcels_seed.json.gz）があればそれを、
    なければ kouzu_xml_data.js（5図面・595筆）を使う。
    ID はシードに含めない（投入時に parcels.id へサロゲートキーが振られる）。"""
    if os.path.exists(PARCEL_SEED_PATH):
        with gzip.open(PARCEL_SEED_PATH, "rt", encoding="utf-8") as f:
            data = json.load(f)
        return data["parcels"], os.path.basename(PARCEL_SEED_PATH)
    rows = [
        {
            "oaza": f["properties"].get("oaza", ""),
            "chome": f["properties"].get("chome", "") or "",
            "chiban": f["properties"]["chiban"],
            "geometry": f["geometry"],
        }
        for f in _load_kouzu_features()
    ]
    return rows, os.path.basename(KOUZU_JS_PATH)


def _kanji_number(n):
    """1〜99 の整数を漢数字にする（位置参照情報の丁目表記に合わせる用）。"""
    ones = "一二三四五六七八九"
    if not 1 <= n <= 99:
        raise ValueError(f"漢数字に変換できない丁目です: {n}")
    if n < 10:
        return ones[n - 1]
    tens, rem = divmod(n, 10)
    return (ones[tens - 1] if tens > 1 else "") + "十" + (ones[rem - 1] if rem else "")


def _seed_town_name(oaza, chome):
    """筆シードの (大字, 丁目) → 位置参照情報の大字町丁目名。
    シード側の丁目は算用数字（例 '３丁目'）、住所マスタ側は漢数字（例 '上野三丁目'）
    のため、突合時にここで表記を合わせる。"""
    if not chome:
        return oaza
    m = re.fullmatch(r"([0-9０-９]+)丁目", chome)
    if not m:
        raise RuntimeError(f"丁目の表記を解釈できません: {oaza}{chome}")
    n = int("".join(chr(ord(c) - 0xFEE0) if c >= "０" else c for c in m.group(1)))
    return oaza + _kanji_number(n) + "丁目"


def seed_address_master_if_empty(conn):
    """住所マスタ（prefectures / shikuchoson / chibankuiki）を位置参照情報 CSV から投入する。"""
    n = conn.execute("SELECT count(*) AS n FROM chibankuiki").fetchone()["n"]
    if n > 0:
        return False
    with open(ADDRESS_CSV_PATH, encoding="shift_jis", newline="") as f:
        rows = list(csv.DictReader(f))
    pref_ids = {}  # 都道府県 jis_code → prefectures.id
    muni_ids = {}  # 市区町村 jis_code → shikuchoson.id
    for r in rows:
        pcode = r["都道府県コード"]
        if pcode not in pref_ids:
            pref_ids[pcode] = conn.execute(
                "INSERT INTO prefectures (jis_code, name) VALUES (%s, %s) RETURNING id",
                (pcode, r["都道府県名"]),
            ).fetchone()["id"]
        mcode = r["市区町村コード"]
        if mcode not in muni_ids:
            muni_ids[mcode] = conn.execute(
                """INSERT INTO shikuchoson (prefecture_id, jis_code, name)
                   VALUES (%s, %s, %s) RETURNING id""",
                (pref_ids[pcode], mcode, r["市区町村名"]),
            ).fetchone()["id"]
        conn.execute(
            """INSERT INTO chibankuiki (shikuchoson_id, choaza_code, name, lat, lng)
               VALUES (%s, %s, %s, %s, %s)""",
            (
                muni_ids[mcode],
                # 大字町丁目コード12桁の下6桁（大字下3桁+丁目3桁）。国土地理協会コード互換
                r["大字町丁目コード"][-6:],
                r["大字町丁目名"],
                float(r["緯度"]), float(r["経度"]),
            ),
        )
    print(
        f"住所マスタを投入しました: {len(pref_ids)} 都道府県・{len(muni_ids)} 市区町村・"
        f"{len(rows)} 地番区域（{os.path.basename(ADDRESS_CSV_PATH)}）"
    )
    return True


def seed_parcels_if_empty(conn):
    n = conn.execute("SELECT count(*) AS n FROM parcels").fetchone()["n"]
    if n > 0:
        return False
    parcels, source = _load_seed_parcels()
    town_ids = {
        r["name"]: r["id"]
        for r in conn.execute("SELECT id, name FROM chibankuiki").fetchall()
    }
    # 5万筆規模になるため COPY で一括投入する（id は IDENTITY が自動採番。
    # 単一 COPY ストリームなので採番順 = シードの出現順になり、ORDER BY id で安定する）
    with conn.cursor() as cur:
        with cur.copy(
            "COPY parcels (chibankuiki_id, chiban, geometry) FROM STDIN"
        ) as copy:
            for p in parcels:
                name = _seed_town_name(p["oaza"], p["chome"])
                town_id = town_ids.get(name)
                if town_id is None:
                    raise RuntimeError(
                        f"地番区域マスタに存在しない町名です: {name}。"
                        f"{os.path.basename(ADDRESS_CSV_PATH)} を更新してください"
                    )
                copy.write_row((
                    town_id, p["chiban"],
                    json.dumps(p["geometry"], separators=(",", ":")),
                ))
    print(f"筆マスタを投入しました: {len(parcels):,} 筆（{source}）")
    return True


# ============================================================
# 導出ヘルパー（旧 data.js の筆マスタ・幾何ヘルパーの移植）
# ============================================================

def parcel_ring(geometry):
    """GeoJSON リング（[lng,lat]・末尾は始点の繰り返し）→ [[lat,lng]]"""
    return [[lat, lng] for lng, lat in geometry["coordinates"][0][:-1]]


def polygon_area_tsubo(latlngs):
    """[[lat,lng]] ポリゴンの面積を坪で返す（重心緯度での平面近似 + 靴ひも公式）。"""
    if not latlngs or len(latlngs) < 3:
        return 0
    lat0 = sum(p[0] for p in latlngs) / len(latlngs)
    lng0 = latlngs[0][1]
    m_per_lat = 111320
    m_per_lng = 111320 * math.cos(math.radians(lat0))
    pts = [((lng - lng0) * m_per_lng, (lat - lat0) * m_per_lat) for lat, lng in latlngs]
    area2 = 0.0
    for i in range(len(pts)):
        x1, y1 = pts[i]
        x2, y2 = pts[(i + 1) % len(pts)]
        area2 += x1 * y2 - x2 * y1
    sqm = abs(area2) / 2
    return round(sqm / 3.305785 * 100) / 100


def convex_hull(points):
    """点群の凸包（Andrew's monotone chain）。サンプル案件の領域自動生成に使う。"""
    pts = sorted(points)
    if len(pts) < 3:
        return pts

    def cross(o, a, b):
        return (a[0] - o[0]) * (b[1] - o[1]) - (a[1] - o[1]) * (b[0] - o[0])

    lower = []
    for p in pts:
        while len(lower) >= 2 and cross(lower[-2], lower[-1], p) <= 0:
            lower.pop()
        lower.append(p)
    upper = []
    for p in reversed(pts):
        while len(upper) >= 2 and cross(upper[-2], upper[-1], p) <= 0:
            upper.pop()
        upper.append(p)
    return lower[:-1] + upper[:-1]


# ============================================================
# JSON シリアライズ（フロントの既存データ形と同じ camelCase）
# ============================================================

def _num(v):
    """numeric → JSON 数値。整数値は int にして「500.0%」のような表示を避ける。"""
    if v is None:
        return None
    f = float(v)
    return int(f) if f.is_integer() else f


def _iso(dt):
    return dt.isoformat() if dt is not None else None


def _visit_json(row):
    return {
        "id": row["id"],
        "user": row["user_name"],
        "comment": row["comment"],
        "date": _iso(row["date"]),
        "directOrTel": row["direct_or_tel"],
        "meetingType": row["meeting_type"],
        "nextDate": _iso(row["next_date"]) or "",
        "progress": row["progress"],
        "principal": row["principal"],
    }


def _land_json(row, visits=None):
    """lands × parcels × chibankuiki の JOIN 行 → Land JSON。
    aza/chiban/polygon は筆マスタ・地番区域マスタから導出。"""
    land = {
        "id": row["id"],
        "parcelId": row["parcel_id"],
        "aza": row["aza"],
        "chiban": row["chiban"],
        "owners": row["owners"],
        "description": row["description"],
        "areaTsubo": _num(row["area_tsubo"]),
        "status": row["status"],
        "createdAt": _iso(row["created_at"]),
        "updatedAt": _iso(row["updated_at"]),
        "polygon": parcel_ring(row["geometry"]),
    }
    if visits is not None:
        land["visits"] = visits
    return land


def _project_json(row, lands=None):
    proj = {
        "id": str(row["id"]),
        "name": row["name"],
        "description": row["description"],
        "createdAt": _iso(row["created_at"]),
        "updatedAt": _iso(row["updated_at"]),
        "polygon": row["polygon"],
        "address": row["address"],
        "access": row["access"],
        "currentFar": _num(row["current_far"]),
        "targetFar": _num(row["target_far"]),
        "frontRoads": row["front_roads"],
    }
    if lands is not None:
        proj["lands"] = lands
    return proj


_LAND_SELECT = """
    SELECT l.*, c.name AS aza, p.chiban, p.geometry,
           COALESCE((
             SELECT jsonb_agg(jsonb_build_object(
                      'name', o.name,
                      'share', CASE WHEN o.share_num IS NOT NULL
                                    THEN o.share_num || '/' || o.share_den ELSE '' END
                    ) ORDER BY o.id)
               FROM land_owners o WHERE o.land_id = l.id
           ), '[]'::jsonb) AS owners
      FROM lands l
      JOIN parcels p ON p.id = l.parcel_id
      JOIN chibankuiki c ON c.id = p.chibankuiki_id
"""


def _parse_project_id(project_id):
    try:
        return int(project_id)
    except (TypeError, ValueError):
        raise ApiError(404, "案件が見つかりません")


def _parse_parcel_id(parcel_id):
    """API から来た parcelId（文字列のことがある）を int に正規化する。"""
    try:
        return int(parcel_id)
    except (TypeError, ValueError):
        raise ApiError(400, "筆マスタに存在しない筆です")


def _parse_dt(value, fallback=None):
    """ISO 文字列（'Z' 終端含む）→ datetime。空・不正は fallback。"""
    if not value:
        return fallback
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00"))
    except ValueError:
        return fallback


# ============================================================
# 読み出し
# ============================================================

def get_parcel_towns(conn):
    """町名（地番区域）の一覧と筆数。土地の追加モード等のプルダウン用。"""
    rows = conn.execute(
        """SELECT c.name, count(*) AS n
             FROM parcels p JOIN chibankuiki c ON c.id = p.chibankuiki_id
            GROUP BY c.id, c.name ORDER BY c.name"""
    ).fetchall()
    return [{"name": r["name"], "count": r["n"]} for r in rows]


def get_parcels_by_town(conn, town, with_geometry=False):
    """指定町名の筆一覧。プルダウンの選択肢用は属性のみ（parcelId と地番）。
    with_geometry=True で領域 [[lat,lng]] 付き（土地の追加モードの候補筆表示用）。"""
    cols = "p.id, p.chiban" + (", p.geometry" if with_geometry else "")
    rows = conn.execute(
        f"""SELECT {cols}
             FROM parcels p JOIN chibankuiki c ON c.id = p.chibankuiki_id
            WHERE c.name = %s ORDER BY p.id""",
        (town,),
    ).fetchall()
    if with_geometry:
        return [
            {"parcelId": r["id"], "chiban": r["chiban"], "polygon": parcel_ring(r["geometry"])}
            for r in rows
        ]
    return [{"parcelId": r["id"], "chiban": r["chiban"]} for r in rows]


def get_parcels(conn):
    """筆マスタ全件。旧 KOUZU_XML_DATA.geojson と同じ features 形で返す（デバッグ用）。"""
    rows = conn.execute(
        """SELECT p.*, c.name AS town_name
             FROM parcels p JOIN chibankuiki c ON c.id = p.chibankuiki_id
            ORDER BY p.id"""
    ).fetchall()
    features = [
        {
            "type": "Feature",
            "properties": {
                "parcelId": r["id"],
                "chibankuikiId": r["chibankuiki_id"],
                "chibankuikiName": r["town_name"],
                "chiban": r["chiban"],
            },
            "geometry": r["geometry"],
        }
        for r in rows
    ]
    return {"features": features}


def get_projects_tree(conn):
    """全案件を lands・visits 込みのツリーで返す（3 クエリで組み立て）。"""
    proj_rows = conn.execute("SELECT * FROM projects ORDER BY id").fetchall()
    land_rows = conn.execute(_LAND_SELECT + " ORDER BY l.project_id, l.created_at, l.id").fetchall()
    visit_rows = conn.execute("SELECT * FROM visits ORDER BY land_id, date, id").fetchall()

    visits_by_land = {}
    for v in visit_rows:
        visits_by_land.setdefault(v["land_id"], []).append(_visit_json(v))

    lands_by_proj = {}
    for l in land_rows:
        lands_by_proj.setdefault(l["project_id"], []).append(
            _land_json(l, visits_by_land.get(l["id"], []))
        )

    return [_project_json(p, lands_by_proj.get(p["id"], [])) for p in proj_rows]


# ============================================================
# 案件 CRUD
# ============================================================

def create_project(conn, fields):
    name = (fields.get("name") or "").strip()
    if not name:
        raise ApiError(400, "案件名は必須です")
    row = conn.execute(
        """INSERT INTO projects (name, description, polygon)
           VALUES (%s, %s, %s) RETURNING *""",
        (name, fields.get("description") or "", Jsonb(fields["polygon"]) if fields.get("polygon") else None),
    ).fetchone()
    return _project_json(row, lands=[])


# PATCH で受け付けるフィールド → (カラム名, 値変換)
_PROJECT_FIELD_COLS = {
    "name": ("name", lambda v: (v or "").strip()),
    "description": ("description", lambda v: v or ""),
    "polygon": ("polygon", lambda v: Jsonb(v) if v else None),
    "address": ("address", lambda v: v),
    "access": ("access", lambda v: v),
    "currentFar": ("current_far", lambda v: v),
    "targetFar": ("target_far", lambda v: v),
    "frontRoads": ("front_roads", lambda v: Jsonb(v if isinstance(v, list) else [])),
}


def update_project(conn, project_id, fields):
    pid = _parse_project_id(project_id)
    if "name" in fields and not (fields["name"] or "").strip():
        raise ApiError(400, "案件名は必須です")
    sets, params = [], []
    for key, (col, conv) in _PROJECT_FIELD_COLS.items():
        if key in fields:
            sets.append(f"{col} = %s")
            params.append(conv(fields[key]))
    sets.append("updated_at = now()")
    row = conn.execute(
        f"UPDATE projects SET {', '.join(sets)} WHERE id = %s RETURNING *",
        params + [pid],
    ).fetchone()
    if not row:
        raise ApiError(404, "案件が見つかりません")
    return _project_json(row)  # lands はクライアント側で保持しているので含めない


def delete_project(conn, project_id):
    pid = _parse_project_id(project_id)
    deleted = conn.execute("DELETE FROM projects WHERE id = %s", (pid,)).rowcount
    if not deleted:
        raise ApiError(404, "案件が見つかりません")


# ============================================================
# 土地 CRUD
# ============================================================

def _parse_share(share):
    """持分文字列 '1520/6755' → (分子, 分母)。分数として解釈できなければ (None, None)。"""
    s = (share or "").strip()
    if "/" not in s:
        return None, None
    num, _, den = s.partition("/")
    try:
        num, den = int(num.strip()), int(den.strip())
    except ValueError:
        return None, None
    return (num, den) if den > 0 else (None, None)


def _replace_owners(conn, land_id, owners):
    """土地の地権者を全置換する（DELETE 旧 + INSERT 新）。name 空は捨てる。"""
    conn.execute("DELETE FROM land_owners WHERE land_id = %s", (land_id,))
    for o in owners or []:
        name = (o.get("name") or "").strip()
        if not name:
            continue
        num, den = _parse_share(o.get("share"))
        conn.execute(
            "INSERT INTO land_owners (land_id, name, share_num, share_den) VALUES (%s, %s, %s, %s)",
            (land_id, name, num, den),
        )


def _fetch_parcel(conn, parcel_id):
    row = conn.execute(
        "SELECT * FROM parcels WHERE id = %s", (_parse_parcel_id(parcel_id),)
    ).fetchone()
    if not row:
        raise ApiError(400, "筆マスタに存在しない筆です")
    return row


def _fetch_land_joined(conn, project_id, land_id):
    row = conn.execute(
        _LAND_SELECT + " WHERE l.project_id = %s AND l.id = %s", (project_id, land_id)
    ).fetchone()
    if not row:
        raise ApiError(404, "土地が見つかりません")
    return row


def create_land(conn, project_id, fields):
    pid = _parse_project_id(project_id)
    if not conn.execute("SELECT 1 FROM projects WHERE id = %s", (pid,)).fetchone():
        raise ApiError(404, "案件が見つかりません")
    parcel = _fetch_parcel(conn, fields.get("parcelId"))
    status = fields.get("status") or "target"
    if status not in ("target", "acquired"):
        raise ApiError(400, "不正なステータスです")
    area = fields.get("areaTsubo")
    if area is None:
        area = polygon_area_tsubo(parcel_ring(parcel["geometry"]))
    land_id = _uuid()
    try:
        conn.execute(
            """INSERT INTO lands (id, project_id, parcel_id, description, area_tsubo, status)
               VALUES (%s, %s, %s, %s, %s, %s)""",
            (
                land_id, pid, parcel["id"],
                fields.get("description") or "", area, status,
            ),
        )
    except psycopg.errors.UniqueViolation:
        raise ApiError(409, "この筆はすでにこの案件に追加済みです")
    _replace_owners(conn, land_id, fields.get("owners"))
    row = conn.execute(
        _LAND_SELECT + " WHERE l.project_id = %s AND l.parcel_id = %s",
        (pid, parcel["id"]),
    ).fetchone()
    conn.execute("UPDATE projects SET updated_at = now() WHERE id = %s", (pid,))
    return _land_json(row, visits=[])


def update_land(conn, project_id, land_id, fields):
    pid = _parse_project_id(project_id)
    land = _fetch_land_joined(conn, pid, land_id)

    sets, params = [], []
    # 筆の付け替え: マスタに存在する parcelId のみ受け付け、坪数を再導出する
    if fields.get("parcelId") is not None and _parse_parcel_id(fields["parcelId"]) != land["parcel_id"]:
        parcel = _fetch_parcel(conn, fields["parcelId"])
        sets += ["parcel_id = %s", "area_tsubo = %s"]
        params += [parcel["id"], polygon_area_tsubo(parcel_ring(parcel["geometry"]))]
    if "owners" in fields:
        _replace_owners(conn, land_id, fields["owners"] if isinstance(fields["owners"], list) else [])
    if "description" in fields:
        sets.append("description = %s")
        params.append(fields["description"] or "")
    if "areaTsubo" in fields and fields["areaTsubo"] is not None:
        sets.append("area_tsubo = %s")
        params.append(fields["areaTsubo"])
    if "status" in fields:
        if fields["status"] not in ("target", "acquired"):
            raise ApiError(400, "不正なステータスです")
        sets.append("status = %s")
        params.append(fields["status"])
    sets.append("updated_at = now()")

    try:
        conn.execute(
            f"UPDATE lands SET {', '.join(sets)} WHERE id = %s", params + [land_id]
        )
    except psycopg.errors.UniqueViolation:
        raise ApiError(409, "この筆はすでにこの案件に追加済みです")
    return _land_json(_fetch_land_joined(conn, pid, land_id))  # visits はクライアント側で保持


def delete_land(conn, project_id, land_id):
    pid = _parse_project_id(project_id)
    deleted = conn.execute(
        "DELETE FROM lands WHERE project_id = %s AND id = %s", (pid, land_id)
    ).rowcount
    if not deleted:
        raise ApiError(404, "土地が見つかりません")


# ============================================================
# 訪問記録（追加のみ。履歴のため編集・削除は提供しない）
# ============================================================

def add_visit(conn, project_id, land_id, fields):
    pid = _parse_project_id(project_id)
    _fetch_land_joined(conn, pid, land_id)
    row = conn.execute(
        """INSERT INTO visits (id, land_id, user_name, comment, date,
                               direct_or_tel, meeting_type, next_date, progress, principal)
           VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s) RETURNING *""",
        (
            _uuid(), land_id,
            fields.get("user") or "", fields.get("comment") or "",
            _parse_dt(fields.get("date"), fallback=_now()),
            fields.get("directOrTel") or "", fields.get("meetingType") or "",
            _parse_dt(fields.get("nextDate")),
            fields.get("progress") or "", fields.get("principal") or "principal",
        ),
    ).fetchone()
    # 訪問追加も土地の活動なので、土地の更新日を進める
    conn.execute("UPDATE lands SET updated_at = now() WHERE id = %s", (land_id,))
    return _visit_json(row)


# ============================================================
# サンプルデータ（旧 data.js makeSampleProjects の移植）
# 登記所備付地図データの実筆から案件・土地を組み立てる。
# ============================================================

OWNER_POOL = [
    "佐藤誠一", "鈴木美津子", "高橋豊", "田中靖子", "伊藤博", "渡辺久美子",
    "山本健二", "中村文夫", "小林千代", "加藤正義", "吉田春子", "山田隆",
    "佐々木幸雄", "山口和子", "松本守", "井上静江", "木村洋一", "林芳子",
    "斎藤勝", "清水トミ", "森田一郎", "池田梅子",
]

# サンプル案件が使う筆の地番リスト（登記所備付地図データの公共座標4図面の全筆。
# 筆は「町名 + 地番」で引く — 地番は地番区域内で一意なので、これで筆が一意に決まる）
_NEGISHI_CHIBANS = [  # 旧図面 13106-0105-142（根岸三丁目・22筆）
    "16-5", "16-6", "24-8", "24-9", "31-11", "31-12", "31-13", "31-14",
    "31-15", "31-16", "31-17", "31-18", "31-19", "31-20", "16-12", "16-11",
    "16-10", "16-9", "16-7", "16-8", "86-7", "31-10",
]
_UENO_CHIBANS = [  # 旧図面 13106-0105-143（上野三丁目・8筆）
    "141-1", "141-2", "141-7", "141-6", "141-5", "141-4", "141-3", "142",
]
_AKIHABARA_CHIBANS = [  # 旧図面 13106-0105-141（秋葉原・4筆）
    "101", "102", "103", "100",
]
_UENO_DAINI_CHIBANS = [  # 旧図面 13106-0105-140（上野三丁目・18筆）
    "23-1", "23-2", "134-1", "134-2", "138-1", "138-2", "139", "140-1",
    "140-2", "140-5", "140-8", "140-4", "140-6", "140-7", "137-2", "137-3",
    "137-1", "137-4",
]

# 案件1（新東京旅館）の領域ポリゴン（実測由来の固定値）
_BASE_POLYGON = [
    [35.712527309087434, 139.78921696543694],
    [35.71248974141639, 139.78941813111305],
    [35.71239064979333, 139.78940404951575],
    [35.712409978114074, 139.78932894766334],
    [35.71233810940472, 139.78930748999122],
    [35.712346820766875, 139.7892585396767],
    [35.71236424348836, 139.78926457464698],
    [35.712384932965136, 139.78917472064495],
]


def _t(days):
    return _now() - timedelta(days=days)


def _t_at(days, hour, minute=0):
    return _t(days).replace(hour=hour, minute=minute, second=0, microsecond=0)


def _visit(user, comment, date, direct_or_tel, meeting_type, next_date, progress, principal):
    return {
        "user": user, "comment": comment, "date": date,
        "directOrTel": direct_or_tel, "meetingType": meeting_type,
        "nextDate": next_date, "progress": progress, "principal": principal,
    }


def _sample_projects(conn):
    """サンプル案件 5 件を dict ツリーで組み立てる（DB 挿入は _insert_sample で行う）。"""

    def parcels_by_chibans(town, chibans):
        rows = conn.execute(
            """SELECT p.* FROM parcels p JOIN chibankuiki c ON c.id = p.chibankuiki_id
                WHERE c.name = %s AND p.chiban = ANY(%s)""",
            (town, chibans),
        ).fetchall()
        by_chiban = {r["chiban"]: r for r in rows}
        # overrides がインデックス参照のため、地番リストの並びを保って返す
        return [by_chiban[cb] for cb in chibans if cb in by_chiban]

    def land_from_parcel(parcel, idx, **overrides):
        land = {
            "parcelId": parcel["id"],
            "owners": [{"name": OWNER_POOL[idx % len(OWNER_POOL)], "share": ""}],
            "description": "",
            "areaTsubo": polygon_area_tsubo(parcel_ring(parcel["geometry"])),
            "status": "target",
            "createdAt": _t(9),
            "updatedAt": _t(2),
            "visits": [],
            "_ring": parcel_ring(parcel["geometry"]),
        }
        land.update(overrides)
        return land

    def build_project(pid, town, chibans, meta, overrides=None):
        feats = parcels_by_chibans(town, chibans)
        lands = [
            land_from_parcel(f, i, **(overrides or {}).get(i, {}))
            for i, f in enumerate(feats)
        ]
        all_pts = [tuple(pt) for l in lands for pt in l["_ring"]]
        proj = {
            "id": pid,
            "createdAt": _t(10),
            "updatedAt": _t(1),
            "polygon": [list(p) for p in convex_hull(all_pts)] if len(all_pts) >= 3 else None,
            "frontRoads": [],
            "lands": lands,
        }
        proj.update(meta)
        return proj

    def nishi_asakusa_land(chiban, **overrides):
        # 筆は属性（町名+地番）で引く。ID はサロゲートキーなので検索キーには使わない
        parcel = conn.execute(
            """SELECT p.* FROM parcels p JOIN chibankuiki c ON c.id = p.chibankuiki_id
                WHERE c.name = %s AND p.chiban = %s""",
            ("西浅草二丁目", chiban),
        ).fetchone()
        if not parcel:
            return None
        return land_from_parcel(parcel, 0, **{"owners": [], **overrides})

    # ----- 案件1: 新東京旅館（西浅草2-4-8・実筆4筆） -----
    shin_tokyo = {
        "id": 1,
        "name": "新東京旅館",
        "description": "駅東口・商業地のオフィスビル建設用地として、隣接する4筆をまとめて地上げ",
        "createdAt": _t(10),
        "updatedAt": _t(1),
        "polygon": _BASE_POLYGON,
        "address": "東京都台東区西浅草2-4-8",
        "access": "東京メトロ銀座線「田原町」駅 徒歩5分 / つくばエクスプレス「浅草」駅 徒歩5分",
        "currentFar": 500,
        "targetFar": 457,
        "frontRoads": [
            {"edgeIndex": 0, "width": 6},
            {"edgeIndex": 1, "width": 6},
        ],
        "lands": [l for l in [
            nishi_asakusa_land(
                "24-3",
                owners=[{"name": "安野政子", "share": ""}],
                description="個人名義（安野氏）。世帯主と早期に条件合意し、所有権移転登記まで完了済み",
                status="acquired", createdAt=_t(8), updatedAt=_t(3),
                visits=[
                    _visit("木村", "初回訪問。安野様にご挨拶し、再開発計画の概要を説明。本人は売却に前向き。",
                           _t(8), "直", "面談(対面)", _t(5), "B", "principal"),
                    _visit("木村", "条件合意。売買契約締結・所有権移転登記完了。",
                           _t(3), "直", "面談(対面)", None, "初期見込み", "principal"),
                ],
            ),
            nishi_asakusa_land(
                "23-1",
                owners=[
                    {"name": "中嶋幸子", "share": "1520/6755"},
                    {"name": "中嶋直美", "share": "5235/6755"},
                ],
                description="中嶋家2名の共有名義（持分比は不均等）。主たる持分を握る中嶋直美氏が窓口となり、所有権移転登記完了",
                status="acquired", createdAt=_t(6), updatedAt=_t(6),
                visits=[
                    _visit("木村", "持分の多い中嶋直美氏が窓口となり、共有者全員から押印取得。所有権移転登記完了。",
                           _t(6), "直", "面談(対面)", None, "初期見込み", "principal"),
                ],
            ),
            nishi_asakusa_land(
                "24-6",
                owners=[{"name": "安野政子", "share": ""}],
                description="個人名義（安野氏）の小規模筆。隣地 24-3 と一体活用を前提に交渉、スムーズに取得完了",
                status="acquired", createdAt=_t(7), updatedAt=_t(4),
                visits=[
                    _visit("本田", "24-3 取得を踏まえ、隣接小筆として安野様と再協議。条件合意・所有権移転登記完了。",
                           _t(4), "TEL", "面談(ITP)", None, "初期見込み", "principal"),
                ],
            ),
            nishi_asakusa_land(
                "24-5",
                owners=[{"name": "株式会社メイクス", "share": ""}],
                description="法人名義。代表と面談中、社内決裁を待っている段階",
                status="target", createdAt=_t(4), updatedAt=_t(1),
                visits=[
                    _visit("本田", "初回訪問。代表に再開発の趣旨を説明、社内検討のため資料を持ち帰り。",
                           _t(4), "直", "面談(対面)", _t(2), "初期見込み", "principal"),
                    _visit("木村", "代表より社内決裁待ちとの回答。次回は最終条件を提示予定。",
                           _t(1), "TEL", "面談(ITP)", _t_at(-2, 15, 30), "B", "non_principal"),
                ],
            ),
        ] if l],
    }

    # ----- 案件2: 根岸三丁目計画（区画整理地区・22筆） -----
    negishi_overrides = {
        0: {
            "status": "acquired", "updatedAt": _t(5),
            "visits": [
                _visit("佐藤", "地権者と条件合意。売買契約締結・所有権移転登記完了。",
                       _t(5), "直", "面談(対面)", None, "初期見込み", "principal"),
            ],
        },
        5: {"status": "acquired", "updatedAt": _t(5)},
        9: {"status": "acquired", "updatedAt": _t(4)},
    }

    # ----- 案件3: 上野三丁目計画（8筆） -----
    ueno_overrides = {
        0: {
            "status": "acquired", "updatedAt": _t(3),
            "visits": [
                _visit("佐藤", "地権者と条件合意。売買契約締結・所有権移転登記完了。",
                       _t(3), "直", "面談(対面)", None, "初期見込み", "principal"),
            ],
        },
        2: {
            "description": "相続登記が未了の可能性あり。法定相続人の調査から着手",
            "visits": [
                _visit("佐藤", "現地訪問するも空き家。近隣ヒアリングでは所有者は数年前に死去、相続人は遠方在住とのこと。",
                       _t(2), "直", "面談(対面)", _t(-3), "C", "other"),
            ],
        },
    }

    return [
        shin_tokyo,
        build_project(2, "根岸三丁目", _NEGISHI_CHIBANS, {
            "name": "根岸三丁目計画",
            "description": "区画整理済みの整形地22筆を一体で取得し、共同住宅用地として開発する大型案件",
            "address": "東京都台東区根岸3丁目",
            "access": "JR山手線「鶯谷」駅 徒歩5分",
            "currentFar": 400,
            "targetFar": 480,
        }, negishi_overrides),
        build_project(3, "上野三丁目", _UENO_CHIBANS, {
            "name": "上野三丁目計画",
            "description": "御徒町駅至近の商業地。中規模オフィスビル建設用地として8筆を取りまとめ",
            "address": "東京都台東区上野3丁目",
            "access": "JR山手線「御徒町」駅 徒歩3分 / 東京メトロ銀座線「上野広小路」駅 徒歩4分",
            "currentFar": 600,
            "targetFar": 700,
        }, ueno_overrides),
        build_project(4, "秋葉原", _AKIHABARA_CHIBANS, {
            "name": "秋葉原計画",
            "description": "秋葉原駅近接の4筆。隣接地権者の意向確認を開始した初期段階の案件",
            "address": "東京都台東区秋葉原",
            "access": "JR山手線「秋葉原」駅 徒歩4分",
            "currentFar": 600,
            "targetFar": 600,
        }),
        build_project(5, "上野三丁目", _UENO_DAINI_CHIBANS, {
            "name": "上野三丁目第二計画",
            "description": "上野三丁目計画の隣接街区18筆。第一計画の進捗を見ながら順次接触予定",
            "address": "東京都台東区上野3丁目",
            "access": "JR山手線「御徒町」駅 徒歩4分",
            "currentFar": 600,
            "targetFar": 650,
        }),
    ]


def _insert_samples(conn):
    for proj in _sample_projects(conn):
        conn.execute(
            """INSERT INTO projects (id, name, description, polygon, address, access,
                                     current_far, target_far, front_roads, created_at, updated_at)
               VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
            (
                proj["id"], proj["name"], proj.get("description", ""),
                Jsonb(proj["polygon"]) if proj.get("polygon") else None,
                proj.get("address"), proj.get("access"),
                proj.get("currentFar"), proj.get("targetFar"),
                Jsonb(proj.get("frontRoads", [])),
                proj["createdAt"], proj["updatedAt"],
            ),
        )
        for land in proj["lands"]:
            land_id = _uuid()
            conn.execute(
                """INSERT INTO lands (id, project_id, parcel_id, description,
                                      area_tsubo, status, created_at, updated_at)
                   VALUES (%s, %s, %s, %s, %s, %s, %s, %s)""",
                (
                    land_id, proj["id"], land["parcelId"],
                    land["description"], land["areaTsubo"], land["status"],
                    land["createdAt"], land["updatedAt"],
                ),
            )
            _replace_owners(conn, land_id, land["owners"])
            for v in land["visits"]:
                conn.execute(
                    """INSERT INTO visits (id, land_id, user_name, comment, date,
                                           direct_or_tel, meeting_type, next_date, progress, principal)
                       VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s)""",
                    (
                        _uuid(), land_id, v["user"], v["comment"], v["date"],
                        v["directOrTel"], v["meetingType"], v["nextDate"],
                        v["progress"], v["principal"],
                    ),
                )
    # 明示 ID で挿入したので IDENTITY シーケンスを進めておく
    conn.execute(
        "SELECT setval(pg_get_serial_sequence('projects', 'id'), "
        "(SELECT COALESCE(MAX(id), 1) FROM projects))"
    )


def reset_samples(conn):
    """案件・土地・訪問記録を破棄してサンプルを再投入する（筆マスタは残す）。"""
    conn.execute("TRUNCATE visits, land_owners, lands, projects RESTART IDENTITY CASCADE")
    _insert_samples(conn)
    conn.execute(
        """INSERT INTO app_meta (key, value) VALUES ('seeded', '1')
           ON CONFLICT (key) DO UPDATE SET value = '1'"""
    )


def _check_schema_version(conn):
    """旧スキーマ（parcels に chibankuiki_id がない）の DB を検出して初期化を案内する。
    デモのため ALTER でのマイグレーションは持たない。"""
    if not conn.execute(
        "SELECT 1 FROM information_schema.tables WHERE table_name = 'parcels'"
    ).fetchone():
        return  # 新規 DB
    if not conn.execute(
        """SELECT 1 FROM information_schema.columns
            WHERE table_name = 'parcels' AND column_name = 'chibankuiki_id'"""
    ).fetchone():
        raise RuntimeError(
            "旧スキーマのデータベースです。"
            "`docker compose down -v && docker compose up -d` で初期化してから再起動してください"
        )
    if conn.execute(
        """SELECT 1 FROM information_schema.columns
            WHERE table_name = 'lands' AND column_name = 'owners'"""
    ).fetchone():
        raise RuntimeError(
            "旧スキーマ（lands.owners）のデータベースです。"
            "`docker compose down -v && docker compose up -d` で初期化してから再起動してください"
        )


def init_db():
    """起動時初期化: スキーマ作成 → 住所マスタ投入 → 筆マスタ投入 → 初回のみサンプル投入。
    「全案件を削除した空の状態」は有効なので、シード済みフラグで初回だけ投入する。"""
    with connect() as conn:
        _check_schema_version(conn)
        ensure_schema(conn)
        seed_address_master_if_empty(conn)
        seed_parcels_if_empty(conn)
        seeded = conn.execute(
            "SELECT 1 FROM app_meta WHERE key = 'seeded'"
        ).fetchone()
        if not seeded:
            _insert_samples(conn)
            conn.execute("INSERT INTO app_meta (key, value) VALUES ('seeded', '1')")
